os: linux
dist: bionic
language: cpp
compiler: clang
install: sudo apt-get install libsdl2-dev libsdl2-mixer-dev libsdl2-image-dev zlib1g-dev binutils
before script:
  - cd src
  - sed -i "s/<git-dev>/$(git describe)/" p1xbraten/version.cpp
script: make client
before_deploy:
  - strip sauer_client
  - cd ..
  - mv src/sauer_client linux_64_client
deploy:
  provider: releases
  api_key:
    secure: "NWDEC/4W6UJk7MUcbTM2hvFse+lonfY1LzQ7ql+F/uWeZ+mCy+ELnM27WUGolxQ8/vOM0eXOac1wS2lWkiocNExGUaD3ABy36sQGIVf/QbYn6WLZnJZPYAXu2q0uf9psbpUMnMGBh+atG/yEcQMUb60r4/38Ez/w4NJbpBbYg2zBVZBCDKJtZQLr5OLP7Nz2uLATj49cr1od8SJ0t2zfUTs3TZagxH628xBqDgP4ZW58SMl7OGu1TB+qn/x0JTIsAI26TfYQ3lCCBmgdYHNOtJFgIHOgqvVnoDtnUNtEb2k+RjpWQt6M9+/trC1P2JFh9xyP92B4t10KrEeUkfJ70mBFIyWD0gos5HgwNvea3xP68N2+atE3HT7PLMECwQGXsdvEXS5At7KRcUEEQ+iutSMf1FuXGwvnqHiRdnrVRQYt2hlBFzP6HUGpe9kcOcMsI9p/7y6tQSKxgsOrXLaSmvM74zB1FhpbHegOlyLNKoRHB6K+FvSsp7pe5XrLPMX7TAieXOBJLT6YQztAPjFomDfbK32oXP0nuJV4rsEzqj3h/kJhb5J4mwnGileXd7WUd1pXWvw07dXrJlbQ5UgPNVZQRFOwaWihhKYFdCpAjz+LEC6XWw6N1MpEnR3TOHXNGGiHSdsm/Ik9mt0Y8ubtXWi56L8toWOfloNAiuhY9TM="
  file: 'linux_64_client'
  skip_cleanup: true
  overwrite: true
  on:
    tags: true