image:
  - Visual Studio 2019
  - macOS
platform: x64
configuration: Release

for:
-
  matrix:
    only:
      - image: Visual Studio 2019
  before_build:
    - ps: (Get-Content src/engine/p1xbraten_version.cpp) -replace '<git-dev>', (git describe) | Set-Content src/engine/p1xbraten_version.cpp
    - ps: (Get-Content src/vcpp/sauerbraten.nsi) -replace '<git-dev>', (git describe) | Set-Content src/vcpp/sauerbraten.nsi
  build:
    project: p1xbraten.vcxproj
    verbosity: minimal
  after_build:
    - ps: makensis src/vcpp/sauerbraten.nsi
  artifacts:
  - path: p1xbraten_*_setup.exe
-
  matrix:
    only:
      - image: macOS
  before_build:
    - cd src
    - sed -i '' "s/<git-dev>/$(git describe)/" engine/p1xbraten_version.cpp
  build_script:
    - make client
  after_build:
    - strip sauer_client
    - mv sauer_client ../sauerbraten_universal
    - cd ..
  artifacts:
  - path: sauerbraten_universal

deploy:
- provider: GitHub
  auth_token:
    secure: CFYvYuxU2ihMXihnUfV4covPTRzzKgbgVk/I+ZEqVu39uLIJlMAGqhNXfGm1BNEv
  force_update: true
  on:
    APPVEYOR_REPO_TAG: true