# fly.toml file generated for p2x on 2022-01-24T21:51:29+01:00

app = "p2x"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[[services]]
  internal_port = 28785
  protocol = "udp"

  [services.concurrency]
    hard_limit = 50
    soft_limit = 45
    type = "connections"

  [[services.ports]]
    port = 28785

# opening one UDP port opens all of them, so
# there's no need to configure 28786 separately
